services:
  app:
    build: .
    container_name: node_rag_backend
    command: node server.js
    ports:
      - "8000:8000"
    env_file:
      - .env   # ✅ Load from your local .env file
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads
    restart: always

  worker:
    build: .
    container_name: node_worker
    command: node worker.js
    env_file:
      - .env   # ✅ Load from your local .env file
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
